### PR TITLE
BUGFIX: IndexSet.unreleasedMailimapSet was creating range one longer …

### PR DESCRIPTION
**Pull request by matadan**
…than expected.

### CODE REVIEW

**Comment by klefevre** [comment]
Thanks for the bugfix but unfortunately It's not enough because all `IndexSet` conversion are based on a `CountableClosedRange` basis. If you run LibetpanConversionTests you'll see that lot of tests will fail =/

**Comment by matadan** [comment]
OK :(

**Comment by matadan** [comment]
How do I run the tests?

**Comment by klefevre** [comment]
@matadan To run tests just press ⌘ + U in Xcode.
I've made my own PR based on your changes here #46.
Thanks a lot for having pointed out this bug 👍

**Comment by matadan** [comment]
You’re welcome. Thanks for making this framework in the first place.

**Pull request closed without merging**
